# Build settings
markdown: kramdown

baseurl: "/" # the subpath of your site, e.g. /blog
url: "codelack.me" # the base hostname & protocol for your site

excerpt_separator: <!--more--> 

collections: 
  works:
    output: true

# defaults: 
#   -
#     scope:
#       path: ""
#       type: "works"
#     values:
#       date: "%Y"