# Build settings
markdown: kramdown

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codelack.github.io" # the base hostname & protocol for your site


# collections: 
#   works:
#     output: true

# defaults: 
#   -
#     scope:
#       path: ""
#       type: "works"
#     values:
#       date: "%Y"